create table if not exists public.collections (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    card_id bigint not null references public.cards on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
    );
alter table public.collections enable row level security;

drop policy if exists "Players can read their own collection" on public.collections;
drop policy if exists "Players can create their own collection" on public.collections;
drop policy if exists "Players can update their own collection" on public.collections;

create policy "Players can read their own collection"
  on public.collections for select
  using (auth.uid() = user_id);

create policy "Players can create their own collection"
  on public.collections for insert
  with check (auth.uid() = user_id);

create policy "Players can update their own collection"
  on public.collections for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);